@ECHO OFF
CHCP 65001 >NUL
SETLOCAL
SET TIMECARD_SYSTEM_DIR=%~dp0
SET NODE_PATH=%TIMECARD_SYSTEM_DIR%node\node_modules
"%TIMECARD_SYSTEM_DIR%node\node.exe" "%TIMECARD_SYSTEM_DIR%configure.js"
ENDLOCAL
